name: fyp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  dio: ^5.3.3  # For making HTTP requests
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  audioplayers: ^5.2.1
  google_maps_flutter: ^2.0.10
  location: ^5.0.3
  geolocator: ^10.1.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  firebase_core: ^2.22.0
  firebase_database: ^10.3.4
  get: ^4.6.1
  flutter_otp_text_field: ^1.1.1
  email_otp: ^1.0.4
  file_picker: ^4.0.0
  firebase_storage: ^11.5.3
  path_provider: ^2.0.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.1
  flutter_gif: ^0.0.4
  flutter_animate: ^4.3.0
  flutter_animated_button: ^2.0.3
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  video_player: ^2.8.1
  image_picker_web: ^3.1.1
  lottie: ^2.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  webdev: ^3.0.7

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Times
      fonts:
        - asset: assets/fonts/times/times.ttf
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
    - family: silkscreen
      fonts:
        - asset: assets/fonts/silkscreen/Silkscreen-Bold.ttf
        - asset: assets/fonts/silkscreen/Silkscreen-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images.png
    - assets/logo.png
    - assets/admin.png
    - assets/pic1.png
    - assets/public-safety.png
    - assets/objective.png
    - assets/record.png
    - assets/safe.png
    - assets/community.jpg
    - assets/mapp.jpg
    - assets/notify.png
    - assets/panic.jpg
    - assets/homepage.png
    - assets/alertup.json
    - assets/community.json
    - assets/communityup.json
    - assets/map.json
    - assets/mapup.json
    - assets/reportup.json
    - assets/security.json
    - assets/loading.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
