// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhcF3CgybYcpRRAk3TE-ZvgFlkJRagmgU',
    appId: '1:321253756082:web:9843f6a0837010ea788dab',
    messagingSenderId: '321253756082',
    projectId: 'watchfuleyes-c2a9d',
    authDomain: 'watchfuleyes-c2a9d.firebaseapp.com',
    databaseURL: 'https://watchfuleyes-c2a9d-default-rtdb.firebaseio.com',
    storageBucket: 'watchfuleyes-c2a9d.appspot.com',
    measurementId: 'G-8F4BLRK2W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDex47P0QzSiSZyTW9IJgp-bKxlXnqdLEk',
    appId: '1:321253756082:android:685c64fe972ec26c788dab',
    messagingSenderId: '321253756082',
    projectId: 'watchfuleyes-c2a9d',
    databaseURL: 'https://watchfuleyes-c2a9d-default-rtdb.firebaseio.com',
    storageBucket: 'watchfuleyes-c2a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoqE8UMt0Posl06A4yZvCMI9uD_6SuZV8',
    appId: '1:321253756082:ios:c248b2bfd9519d0e788dab',
    messagingSenderId: '321253756082',
    projectId: 'watchfuleyes-c2a9d',
    databaseURL: 'https://watchfuleyes-c2a9d-default-rtdb.firebaseio.com',
    storageBucket: 'watchfuleyes-c2a9d.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoqE8UMt0Posl06A4yZvCMI9uD_6SuZV8',
    appId: '1:321253756082:ios:b8a069d1d37f18f1788dab',
    messagingSenderId: '321253756082',
    projectId: 'watchfuleyes-c2a9d',
    databaseURL: 'https://watchfuleyes-c2a9d-default-rtdb.firebaseio.com',
    storageBucket: 'watchfuleyes-c2a9d.appspot.com',
    iosBundleId: 'com.example.fyp.RunnerTests',
  );
}
